@extends('layouts/master')
@section('title', 'mgp')
@section('content')

<div class="card mb-2 px-3 pt-3 pb-2">
<div class="row">
    <div class="col-md-2 mb-1"><div class="border p-1 text-center">Actions</div></div>
    <div class="col-md-10 mb-1"><a href="{{url('paramgroupesliste')}}" type="button" class="btn btn-outline-primary">Liste Gr</a> <a href="" type="button" class="btn btn-outline-success">Nouveau</a> <a href="{{url('paramgroupes')}}" type="button" class="btn btn-outline-success">Modifer Gr</a> <a href="" type="button" class="btn btn-danger">Update Gr</a></div>
</div>
</div>

<div class="card mb-2 px-3 pt-3 pb-2">
<div class="row">
    <div class="col-md-1 mb-1"><div class="m-1">Filtres</div></div>
    <div class="col-md-10 mb-1">
        <div class="row">
            <div class="col-md-2 mb-1"><select class="form-control" name="" id=""><option value="">Groupe</option></select></div>
            <div class="col-md-2 mb-1"><select class="form-control" name="" id=""><option value="">Localit&eacute;</option></select></div>
            <div class="col-md-8 mb-1"></div>
        </div>
    </div>
    <div class="col-md-1 mb-1"><button type="button" class="btn btn-dark" data-mdb-ripple-init><i class="fas fa-magnifying-glass"></i></button></div>
</div>
</div>

              <!-- Responsive Table -->
              <div class="card mb-2">
                <div class="table-responsive text-nowrap">
                  <table class="table">
                    <thead>
                      <tr class="text-nowrap">
                        <th>#</th>
                        <th><div class="border p-1 text-center bggris">Groupes</div></th>
                        <th><div class="border p-1 text-center bggris">Localit&eacute;</div></th>
                        <th><div class="border p-1 text-center bggris">IDB</div></th>
                        <th><div class="border p-1 text-center bggris">CLD</div></th>
                        <th><div class="border p-1 text-center bggris">THIMO</div></th>
                        <th><div class="border p-1 text-center bggris">TMI</div></th>
                        <th><div class="border p-1 text-center bggris">CERC</div></th>
                        <th><div class="border p-1 text-center bggris">MEDAC</div></th>
                        <th><div class="border p-1 text-center bggris">MGP</div></th>
                        <th><div class="border p-1 text-center bggris">Analyses</div></th>
                        <th><div class="border p-1 text-center bg-warning">MGP-</div></th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">1</th>
                        <td><div class="border p-1 text-center">CTM_NU</div></td>
                        <td><div class="border p-1 text-center">NU</div></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><button class="form-control btn-sm btn-success">Modifier</button></td>
                      </tr>
                      <tr>
                        <th scope="row">2</th>
                        <td><div class="border p-1 text-center">CTIC_SK</div></td>
                        <td><div class="border p-1 text-center">SK</div></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><button class="form-control btn-sm btn-success">Modifier</button></td>
                      </tr>
                      <tr>
                        <th scope="row">3</th>
                        <td><div class="border p-1 text-center">CTHIMO_IT</div></td>
                        <td><div class="border p-1 text-center">IT</div></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><button class="form-control btn-sm btn-success">Modifier</button></td>
                      </tr>
                      <tr>
                        <th scope="row">4</th>
                        <td><div class="border p-1 text-center">CA_SU</div></td>
                        <td><div class="border p-1 text-center">SU</div></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><button class="form-control btn-sm btn-success">Modifier</button></td>
                      </tr>
                      <tr>
                        <th scope="row">5</th>
                        <td><div class="border p-1 text-center">VBG_Team</div></td>
                        <td><div class="border p-1 text-center">SU</div></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><button class="form-control btn-sm btn-success">Modifier</button></td>
                      </tr>
                      <tr>
                        <th scope="row">6</th>
                        <td><div class="border p-1 text-center">Ethiq_Team</div></td>
                        <td><div class="border p-1 text-center">SU</div></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><table width="100%"><tr><td>&nbsp;R</td><td>&nbsp;W</td><td>&nbsp;U</td><td>&nbsp;D</td></tr><tr><td align="center"><input class="form-check-input" type="checkbox" value="" id="" checked /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td><td align="center"><input class="form-check-input" type="checkbox" value="" id="" /></td></tr></table></td>
                        <td><button class="form-control btn-sm btn-success">Modifier</button></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <!--/ Responsive Table -->


@endsection
